#!groovy

def workspace = "~/Users/Shared/Jenkins/Home/jobs/Navigator\ Pipeline/workspace"

// Pull the scripts from ops-script repo
stage 'Script Checkout'
node {
  git credentialsId: '102eded7-0eea-44de-b457-efb71884c99a', url: 'git@bitbucket.org:calmagchiu/ops-scripts.git'
}

// Run save_response.py and save results.csv
stage 'Save_Response Script'
node {
  sh 'python $workspace/compare_navigator_response/save_response.py'
}

// Pull the navigator update
stage 'Navigator Checkout'
node {
  //git credentialsId: '102eded7-0eea-44de-b457-efb71884c99a', url: 'git@bitbucket.org:calmagchiu/navigator.git'
}

// Deploy the navigator update
stage 'Navigator Deployment'
node {

}

// Run compare_response.py and save results csv
stage 'Compare_Response Script'
node {
  //sh 'python $WORKSPACE/compare_navigator_response/compare_response.py'
}

// Wait for manual check of results csv (for regression/check issues)
stage 'Stability Check'
input message: 'Check route_comparison.csv for regression/check issues', ok: 'Accept changes'

// Parallel stage
stage 'Generate Jenkins Test Result csv and Deploy on Sandbox'
parallel(
  // Generate a Jenkins-readable csv
  phase1: {},

  // Deploy the Navigator code on Sandbox
  phase2: {}
)
