#!groovy

// Pull the scripts from ops-script repo
stage 'Script Checkout'
node {

}

// Run save_response.py and save results.csv
stage 'Save_Response Script'
node {

}

// Pull the navigator update
stage 'Navigator Checkout'
node {

}

// Deploy the navigator update
stage 'Navigator Deployment'
node {

}

// Run compare_response.py and save results csv
stage 'Compare_Response Script'
node {

}

// Wait for manual check of results csv (for regression/check issues)
stage 'Stability Check'
node {

}

// Generate a Jenkins-readable csv
// Can run in parallel to 'Deploy on Sandbox'
stage 'Generate Jenkins Test Result csv'
node {

}

// Deploy the Navigator code on Sandbox
stage 'Deploy on Sandbox'
node {

}
