#!groovy

// Pull the scripts from ops-script repo
stage 'Script Checkout'
node {
  dir('ops_scripts') {
    git credentialsId: '102eded7-0eea-44de-b457-efb71884c99a', url: 'git@bitbucket.org:calmagchiu/ops-scripts.git'
  }
}

// Run save_response.py and save results.csv
stage 'Save_Response Script'
node {
  dir('ops_scripts/compare_navigator_response') {
    sh 'python save_response.py'
  }
}

// Pull the navigator update
stage 'Navigator Checkout'
node {
  dir('navigator_files') {
    git credentialsId: '102eded7-0eea-44de-b457-efb71884c99a', url: 'git@bitbucket.org:calmagchiu/navigator.git'
  }
}

// Deploy the navigator update
stage 'Navigator Deployment'
node {
  dir('navigator_files') {
    sh 'scp -i ~/.ssh/Jenkins.pem __init__.py dbf.py earth.py geometry.py navigation.py restart-all.sh restart.sh signs.py titlecase.py ubuntu@52.11.192.135:~/'
  }
}

// Run compare_response.py and save results csv
stage 'Compare_Response Script'
node {
  dir('ops_scripts/compare_navigator_response') {
    sh 'python compare_response.py'
    archiveArtifacts 'route_comparison.csv'
  }
}

// Wait for manual check of results csv (for regression/check issues)
stage 'Stability Check'
node {
  slackSend channel: '#navigator', color: 'good', message: 'Compare_response.py successfully completed. Waiting on engineer to check and approve route_comparison.csv', teamDomain: 'metropia', token: 'G051i0CE8ZtJJUUfH9ntuxta'
}
input message: 'Check route_comparison.csv for regression/check issues', ok: 'Accept changes'


// Parallel stage
stage 'Generate Jenkins Test Result csv and Deploy on Sandbox'
parallel(
  // Generate a Jenkins-readable csv
  phase1: {},

  // Deploy the Navigator code on Sandbox
  phase2: {}
)
