#!groovy

int rollbackNum = "${RollbackFrom}" as Integer

stage('Setup') {
  node('AWS') {
    echo "Rolling back from stage ${RollbackFrom}"
  }
  node('97') {
    if(rollbackNum >= 3) {
      // Set the city name for file path on .97
      def cityUpper="Tucson" //Default
      if("${City}".compareTo("austin")==0) {
        cityUpper="Austin"
      } else if("${City}".compareTo("elpaso_juarez")==0) {
        cityUpper="EP_Juarez"
      } else if("${City}".compareTo("houston")==0) {
        cityUpper="Houston"
      } else if("${City}".compareTo("newyork")==0) {
        cityUpper="NYC"
      } else if("${City}".compareTo("tucson")==0) {
        cityUpper="Tucson"
      }

      // Pull the most recent backup-1 to get the files for the given city
      bat "C:\\Users\\NLarson\\jenkins\\copyBackup.bat ${cityUpper}"
      //stash includes: "INSERT_FILE_IDENTIFIER", name: 'backup_files'
    }
  }
}

stage('Mandel Deploy Stage 2') {
  node('AWS') {
    if(rollbackNum >= 7) {
      // TODO: Need to pull from .97 to get backup files
    } else {
      echo 'Skipping this rollback because of given RollbackFrom value'
    }
  }
}

stage('Trace Deploy Stage 2') {
  node('AWS') {
    if(rollbackNum >= 6) {
      build job: 'Trace_Rollback_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "2")]
    } else {
      echo 'Skipping this rollback because of given RollbackFrom value'
    }
  }
}

stage('Dynamob Deployment') {
  node('master') {
    if(rollbackNum >= 5) {
      // TODO: Need to pull from .97 to get backup files
    } else {
      echo 'Skipping this rollback because of given RollbackFrom value'
    }
  }
}

stage('Parade 1.0/1.5.1 Deployment') {
  node('AWS') {
    if(rollbackNum >= 4) {
      parallel 'Parade 1.0 Deployment':{
        if("${Parade_Version}".compareTo("1.0")==0 || "${Parade_Version}".compareTo("All")==0) {
          build job: 'Parade_1.0_Rollback', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
        }
      }, 'Parade 1.5.1 Deployment': {
        if("${Parade_Version}".compareTo("1.5.1")==0 || "${Parade_Version}".compareTo("All")==0) {
          // TODO: Need to pull from 97 to get backup files
        }
      }
    } else {
      echo 'Skipping this rollback because of given RollbackFrom value'
    }
  }
}

stage('Mandel/WaitTimeModel/Map Matching Deployment') {
  node('AWS') {
    if(rollbackNum >= 3) {
      parallel 'Mandel Deployment': {
        // TODO: Need to pull from .97 to get backup files
      }, 'WaitTimeModel Deployment': {
        if("${City}".compareTo("elpaso_juarez")==0) {
          // TODO: Need to pull from .97 to get backup files
        }
      }, 'Map Matching Deployment': {
        // TODO: Need to pull from .97 to get backup files
      }
    } else {
      echo 'Skipping this rollback because of the given RollbackFrom value'
    }
  }
}

stage('Trace/Crystal/Navigator Deployment') {
  node('AWS') {
    if(rollbackNum >= 2) {
      parallel 'Trace Deployment':{
        build job: 'Trace_Rollback_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "1")]
      }, 'Crystal Deployment':{
        build job: 'Crystal_Rollback', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
      }, 'Navigator Deployment':{
        build job: 'Navigator_Rollback', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
      }
    } else {
      echo 'Skipping this rollback because of the given RollbackFrom value'
    }
  }
}

stage('FFS Deployment') {
  node('AWS') {
    if(rollbackNum >= 1) {
      build job: 'FFS_Rollback', parameters: [string(name: 'City', value: "${City}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
    } else {
      echo 'Skipping this rollback because of the given RollbackFrom value'
    }
  }
}
