#!groovy

stage('FFS Deployment') {
  if("${City}".compareTo("elpaso_juarez")==0) {
    build job: 'FFS_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Env', value: "${Env}")]
  } else {
    build job: 'FFS_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Env', value: "${Env}")]
  }
}

stage('Trace/Crystal/Navigator Deployment') {
  node('AWS') {
    sleep time: 2, unit: 'MINUTES'

    parallel 'Trace Deployment':{
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'Trace_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      } else {
        build job: 'Trace_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      }
    }, 'Crystal Deployment':{
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'Crystal_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      } else {
        build job: 'Crystal_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      }
    }, 'Navigator Deployment':{
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'Navigator_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      } else {
        build job: 'Navigator_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      }
    }

    sleep time: 2, unit: 'MINUTES'
  }
}

stage('Mandel Deployment') {
  node('AWS') {
    build job: 'Mandel_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
  }
}

stage('Parade Deployment') {
  node('AWS') {
    if("${Parade_Version}".compareTo("1.0")==0 || "${Parade_Version}".compareTo("Both")==0) {
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'Parade_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      } else {
        build job: 'Parade_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      }
    }

    if("${Parade_Version}".compareTo("1.5")==0 || "${Parade_Version}".compareTo("Both")==0) {
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'Parade_1.5_Server', parameters: [string(name: 'City', value: "elpaso"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      } else {
        build job: 'Parade_1.5_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
      }
    }
  }
}
