#!groovy

stage('FFS Deployment') {
  build job: 'FFS_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
}

stage('Trace/Crystal/Navigator Deployment') {
  node('AWS') {
    sleep 30

    parallel 'Trace Deployment':{
      build job: 'Trace_Server_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${BUILD_NUMBER}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "1")]
    }, 'Crystal Deployment':{
      build job: 'Crystal_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
    }, 'Navigator Deployment':{
      build job: 'Navigator_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
    }

    sleep 30
  }
}

stage('Mandel/WaitTimeModel/Map Matching Deployment') {
  node('AWS') {
    parallel 'Mandel Deployment': {
      build job: 'Mandel_Server_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${BUILD_NUMBER}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "1")]
    }, 'WaitTimeModel Deployment': {
      if("${City}".compareTo("elpaso_juarez")==0) {
        build job: 'WaitTimeModel_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
      }
    }, 'Map Matching Deployment': {
      build job: 'Map_Matching_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
    }
  }
}

stage('Parade 1.0/1.5.1 Deployment') {
  node('AWS') {
    parallel 'Parade 1.0 Deployment':{
      if("${Parade_Version}".compareTo("1.0")==0 || "${Parade_Version}".compareTo("All")==0) {
        build job: 'Parade_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
      }
    }, 'Parade 1.5.1 Deployment': {
      if("${Parade_Version}".compareTo("1.5.1")==0 || "${Parade_Version}".compareTo("All")==0) {
        build job: 'Parade_1.5_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}"), string(name: 'Deploy_Env', value: "${Deploy_Env}")]
      }
    }
  }
}

stage('Dynamob Deployment') {
  node('master') {
    build job: 'Dynamob_Server', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${ARTIFACT_BUILD}")]
  }
}

stage('Trace Deployment Stage 2') {
  node('AWS') {
    build job: 'Trace_Server_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${BUILD_NUMBER}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "2")]
  }
}

stage('Mandel Deployment Stage 2') {
  node('AWS') {
    build job: 'Mandel_Server_Staged', parameters: [string(name: 'City', value: "${City}"), string(name: 'ARTIFACT_BUILD', value: "${BUILD_NUMBER}"), string(name: 'Deploy_Env', value: "${Deploy_Env}"), string(name: 'Stage', value: "2")]
  }
}
